artifact_uri: teste_2022-10-16/0/edeeaf65cca447d2a3ab3f9d5e245fa0/artifacts
end_time: 1665936357520
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: edeeaf65cca447d2a3ab3f9d5e245fa0
run_uuid: edeeaf65cca447d2a3ab3f9d5e245fa0
source_name: ''
source_type: 4
source_version: ''
start_time: 1665936323254
status: 3
tags: []
user_id: cleit
