artifact_uri: s3://mlflow-bucket-cleiton/b1897d37f8604ed7b2f2f8f1e4985c65/artifacts
end_time: 1665935558155
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b1897d37f8604ed7b2f2f8f1e4985c65
run_uuid: b1897d37f8604ed7b2f2f8f1e4985c65
source_name: ''
source_type: 4
source_version: ''
start_time: 1665935516594
status: 4
tags: []
user_id: cleit
